fix card stacking in community patners page on hover
web3community/web3community.github.io pull request #146
Opened 2021-12-05 08:41 UTC by technophile-04

### Describe the changes you've made

I have enabled the hover variant in tailwind.config.js file for the zIndex utilities so that I can add a class `hover:z-10` to all the cards `div` on the community partners page such that they come up of every `div` and not stay behind of any neighbor `div`.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

N/A

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 <img width="1440" alt="Screenshot 2021-12-05 at 1 31 50 PM" src="https://user-images.githubusercontent.com/80153681/144739682-e241296e-865d-42bd-a7bd-b1209a3d1158.png"> | <img width="1440" alt="Screenshot 2021-12-05 at 1 34 16 PM" src="https://user-images.githubusercontent.com/80153681/144739696-d0825d4b-41c8-483d-8c1f-91d469b79e71.png">|

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

2021-12-05 19:08 UTC, Panquesito7 requested changes
Please revert the changes in `package-lock.json` file.

2021-12-05 19:08 UTC, Panquesito7 commented on tailwind.config.js
> +			zIndex: ['hover'],
This should fix [Codacy Linting](https://app.codacy.com/gh/web3community/web3community.github.io/pullRequest?prid=8517714) warnings. 🙂
```suggestion
			zIndex: ["hover],
```

2021-12-06 02:39 UTC, Panquesito7 approved these changes

2021-12-06 04:33 UTC, krishguptadev approved these changes

2021-12-06 04:40 UTC, vinzvinci approved these changes

2021-12-06 04:40 UTC, merged