social media icons added | issue #18 fixed
web3community/web3community.github.io pull request #20
Opened 2021-09-18 17:23 UTC by 0shivamh

## Related Issue 
fixed #18 issue 
- Information about the related issue 

Closes: # 

### Describe the changes you've made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

2021-09-18 17:39 UTC, 0shivamh commented
HI @vinzvinci  please review it, if there are any changes please let me know

2021-09-19 08:00 UTC, mkubdev reviewed
Hi, good PR. But i think we should use [Tailwind](https://tailwindcss.com/) ..

2021-09-19 12:21 UTC, vinzvinci requested changes
Can you change it to tailwind? 

We like to follow that framework.

2021-09-19 12:23 UTC, 0shivamh commented
> Can you change it to tailwind?
> 
> We like to follow that framework.

Okay, No issue

2021-09-19 12:24 UTC, vinzvinci commented
Thank you :)

2021-09-19 12:45 UTC, 0shivamh commented
> Thank you :)

Can I use .svg for the icon?  or should I continue with fontawesome? , If you have any other suggestions please let me know

2021-09-19 12:56 UTC, vinzvinci commented
> Can I use .svg for the icon? or should I continue with fontawesome? , If you have any other suggestions please let me know

You can use fontawesome

2021-09-19 13:04 UTC, 0shivamh commented
> > Can I use .svg for the icon? or should I continue with fontawesome? , If you have any other suggestions please let me know
> 
> You can use fontawesome

okay, thank you.

2021-09-19 13:10 UTC, Panquesito7 requested changes
Also, there's no screenshot provided. Could you please add some screenshots? Thank you. 🙂

2021-09-19 13:10 UTC, Panquesito7 commented on main.css
> +}
Missing an endline.

2021-09-19 13:10 UTC, Panquesito7 commented on main.css
> +    }
```suggestion
}

```

2021-09-19 13:10 UTC, Panquesito7 commented on main.css
> +
```suggestion
```

2021-09-19 13:10 UTC, Panquesito7 commented on index.html
> +            <!-- </a> -->
```suggestion
            <!-- Social -->
            <!-- </a> -->
```

2021-09-19 13:10 UTC, Panquesito7 commented on main.css
> +.social-icons:hover{
```suggestion
.social-icons:hover {
```

2021-09-19 13:10 UTC, Panquesito7 commented on main.css
> +.social-icons{
```suggestion
.social-icons {
```

2021-09-19 13:52 UTC, 0shivamh commented
> Also, there's no screenshot provided. Could you please add some screenshots? Thank you.

sure

2021-09-19 13:53 UTC, vinzvinci approved these changes
LGTM 👍 We can come up with new ideas if needed.

For final review @mkubdev.

2021-09-19 13:57 UTC, mkubdev commented
LGTM! 👍

2021-09-19 13:58 UTC, Panquesito7 reviewed
Woah! It looks awesome! Great work! 🎉

2021-09-19 13:58 UTC, Panquesito7 commented on index.html
> +            <p class="text-white md:mb-6">Follow Us</p>
```suggestion
            <p class="text-white md:mb-6">Follow us on social media</p>
```

2021-09-19 13:58 UTC, Panquesito7 commented on index.html
> +             <!--socials icons ended-->
```suggestion
            <!--socials icons ended-->
```

2021-09-19 13:59 UTC, merged

2021-09-19 14:01 UTC, 0shivamh commented
> Woah! It looks awesome! Great work!

happy to hear that, thank you

2021-09-19 14:09 UTC, Panquesito7 commented
> LGTM! 👍

My reviews weren't resolved yet 😅 I'll make another PR to fix that.

2021-09-19 14:12 UTC, mkubdev commented
Oops 🤭 sry mate.

2021-09-19 14:13 UTC, Panquesito7 commented
It's alright. I'll make another PR for that if you like it. 🙂