fixed and changed content
web3community/web3community.github.io pull request #63
Opened 2021-10-02 15:01 UTC by pranavvdesai

## Related Issue 

- Changed the content on developer path
Closes: #46 

## Changes

- fixed the pakage.json issue

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

2021-10-02 15:57 UTC, shuklaritvik06 commented
Can you add some ss?

2021-10-02 16:27 UTC, KukretiShubham reviewed
Please show the ss. Now, we have whole card hyperlinked. Would be great, if we have only 'Take me There' button clickable, removed development button. Even this is okay. We can create a separate Issue for that. For now Share the SS.

2021-10-02 16:50 UTC, shuklaritvik06 commented
> Please show the ss. Now, we have whole card hyperlinked. Would be great, if we have only 'Take me There' button clickable, removed development button. Even this is okay. We can create a separate Issue for that. For now Share the SS.

Great suggestion shubham! We can create separate issue for that

2021-10-02 17:46 UTC, pranavvdesai commented
> Please add some ss

yes, only the Take me there button is clickable

![image](https://user-images.githubusercontent.com/74852751/135726864-297cc4c9-2ffe-4694-98d3-586a67f7963b.png)

2021-10-02 18:06 UTC, shuklaritvik06 commented
Hey @pranavvdesai  please resolve the merge conflicts

2021-10-02 18:55 UTC, pranavvdesai commented
> Hey @pranavvdesai please resolve the merge conflicts

Okay will do

2021-10-03 00:39 UTC, Panquesito7 requested changes

2021-10-03 00:39 UTC, Panquesito7 commented on src/index.html
> +                Take Me There!
```suggestion
                Take me there!
```

2021-10-03 00:39 UTC, Panquesito7 commented on src/index.html
> +                Take Me There!
```suggestion
                Take me there!
```

2021-10-03 00:39 UTC, Panquesito7 commented on src/index.html
> +                Take Me There!
```suggestion
                Take me there!
```

2021-10-03 10:34 UTC, vinzvinci reviewed
Can you provide the latest screenshot? 

Please review this @mkubdev

2021-10-03 15:03 UTC, closed without merging

2021-10-03 15:18 UTC, shuklaritvik06 commented
@pranavvdesai why you closed this PR?? You can update this only. It becomes difficult to maintain when you create multiple PR's for one change