changed card content
web3community/web3community.github.io pull request #65
Opened 2021-10-03 15:09 UTC by pranavvdesai

## Related Issue 

- Changed card content on blockchain dev path

Closes: #46 

### Describe the changes you've made

My branch wasn't updated with the responsive changes made, reverted and made changes.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/74852751/135760171-61a14ae9-1f88-4359-ab38-4a7d769e0203.png)

 
## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

2021-10-03 15:34 UTC, shuklaritvik06 commented on src/index.html
> +          <img alt="framer" class="bg-gray-50 p-5 rounded-md" src="./static/img/simplilearn.png" />
Please change alt from framer to simplilearn

2021-10-03 15:35 UTC, shuklaritvik06 commented on src/index.html
> +          <img alt="whimsical" class="bg-gray-50 p-5 rounded-md" src="./static/img/whiteboard.png" />
same change alt here

2021-10-03 15:35 UTC, shuklaritvik06 commented on src/index.html
> +          <img alt="mindmaster" class="bg-gray-50 p-5 rounded-md" src="./static/img/figment.png" />
same here

2021-10-03 15:35 UTC, shuklaritvik06 commented on src/index.html
> +          <img alt="zapier" class="bg-gray-50 p-5 rounded-md" src="./static/img/cryptozombie.png" />
same here

2021-10-03 15:42 UTC, Panquesito7 requested changes
Please see the comments by @shuklaritvik06.

2021-10-03 16:51 UTC, Panquesito7 approved these changes
Awesome! Great work! Thanks. 🚀

2021-10-03 16:52 UTC, shuklaritvik06 approved these changes
LGTM :)

2021-10-03 22:42 UTC, vinzvinci approved these changes
LGTM 👍

2021-10-03 22:42 UTC, merged

2021-10-04 03:39 UTC, KukretiShubham commented
Thanks for the contribution

2021-10-04 08:58 UTC, mkubdev reviewed
Thanks for your contribution